### ISSUE TITLE
shell crashes and needs restarting after sql lexer error [JIRA: RTS-1094]

### ISSUE THREAD

**Issue by seanjensengrey** [basho/riak_shell#33] opened 2016-05-03 18:15 UTC
After attempting to insert into a non-existent table, the SQL Lexer process dies and prevents the shell from accepting any further commands.

```
# this succeeds
riak-shell(6)>INSERT INTO GeoCheckin VALUES ('family2','series2',1420113600700,'snow',12.2);                                               
```

```
# there is no Geo1Checkin table
riak-shell(7)>INSERT INTO Geo1Checkin VALUES ('family2','series2',1420113600700,'snow',12.2);
SQL Lexer error {{function_clause,
                     [{connection_srv,'-handle_call/3-lc$^0/1-0-',
                          [error],
                          [{file,"src/connection_srv.erl"},{line,84}]},
                      {connection_srv,handle_call,3,
                          [{file,"src/connection_srv.erl"},{line,84}]},
                      {gen_server,handle_msg,5,
                          [{file,"gen_server.erl"},{line,585}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,239}]}]},
                 {gen_server,call,
                     [connection_srv,
                      {run_sql_query,
                          "INSERT INTO Geo1Checkin VALUES ('family2','series2',1420113600700,'snow',12.2);"}]}}
```

```
# valid sql continues to recv Lexer errors
riak-shell(8)>select * from GeoCheckin where time >= 1420113600000 and time <= 1420113750001 and region = 'family2' and state = 'series2';
SQL Lexer error {noproc,
                    {gen_server,call,
                        [connection_srv,
                         {run_sql_query,
                             "select * from GeoCheckin where time >= 1420113600000 and time <= 1420113750001 and region = 'family2' and state = 'series2';"}]}}
```

**Comment by Basho-JIRA** [comment] 2016-11-04 14:21
gordonguthrie [2:54 AM]  
Basically `INSERT INTO` doesn’t check if the table exists before trying to use the helper module to create the actual record to be written...

That is the server side of the `UNEXPECTED ERROR` one in `riak-shell`

andreiz [3:00 AM]  
@gordonguthrie @andytill I have a fix for this bug:

[3:01]  
https://github.com/basho/riak_kv/commit/ce00a67712e9010676b2c08693dede664c0e1b2a 

**_[posted via JIRA by Derek Somogyi]**_

**Comment by Basho-JIRA** [comment] 2016-11-07 10:45
The commit above needs to be reverted after https://github.com/basho/riak_kv/pull/1530 is merged because it gives a misleading error message. 

**_[posted via JIRA by Andy Till]**_

**Comment by Basho-JIRA** [comment] 2016-11-18 09:47
This should be fixed - but keep open for regression tests 

**_[posted via JIRA by Gordon Guthrie]**_

**Comment by Basho-JIRA** [comment] 2016-11-22 16:44
Resolving merge conflict regarding where/how to check for table existence. 

***[posted via JIRA by James Gorlick]***

**Closed** 2016-11-28 14:58 UTC
Labels: JIRA: Closed
